"""The .bak -> .sql step. A .bak is a page-image, not a script: nothing can read
object definitions out of one without an engine restoring it first (see PLAN-03
§13/§17). So the real pipeline is .bak -> RESTORE (restore.py) -> live DB -> script
this module -> .sql.

mssql-scripter and `sqlpackage /Action:Script` were both tried and dropped: the
former's bundled runtime needs libssl1.1 (not present on this system), the latter
refuses to generate a full create-script for real production schemas containing
elements it considers "stateful" (SQL74502, hit on this exact data). Both are
fragile, third-party wrappers over information the engine already exposes directly.

Procedures/views/functions/triggers are pulled via sys.sql_modules.definition,
which is the exact original CREATE text -- byte-identical, not a reconstruction.
Tables are reconstructed from INFORMATION_SCHEMA (columns + PK only; indexes,
defaults and FKs are NOT included here since SqlPackage's dacpac diff is the
actual detector for those -- this file is a readable/git-diffable artifact,
not a restore-quality dump).
"""
import pymssql

from . import config

_PROGRAMMABLE_QUERY = """
SELECT s.name AS schema_name, o.name AS obj_name, o.type_desc, m.definition
FROM sys.sql_modules m
JOIN sys.objects o ON m.object_id = o.object_id
JOIN sys.schemas s ON o.schema_id = s.schema_id
WHERE o.type IN ('P','V','FN','IF','TF','TR')
ORDER BY o.type_desc, s.name, o.name
"""

_TABLES_QUERY = """
SELECT s.name AS schema_name, t.name AS table_name
FROM sys.tables t JOIN sys.schemas s ON t.schema_id = s.schema_id
ORDER BY s.name, t.name
"""

_COLUMNS_QUERY = """
SELECT c.name, ty.name AS type_name, c.max_length, c.precision, c.scale, c.is_nullable,
       COALESCE(ic.is_primary_key, 0) AS is_pk
FROM sys.columns c
JOIN sys.types ty ON c.user_type_id = ty.user_type_id
LEFT JOIN (
    SELECT ic.object_id, ic.column_id, i.is_primary_key
    FROM sys.index_columns ic
    JOIN sys.indexes i ON ic.object_id = i.object_id AND ic.index_id = i.index_id
    WHERE i.is_primary_key = 1
) ic ON ic.object_id = c.object_id AND ic.column_id = c.column_id
WHERE c.object_id = OBJECT_ID(%s)
ORDER BY c.column_id
"""

_SIZED_TYPES = {"varchar", "nvarchar", "char", "nchar", "varbinary", "binary"}
_PRECISION_TYPES = {"decimal", "numeric"}


def _connect(db_name, side=None):
    from . import restore
    return restore.open_connection(side, db_name, timeout=60)


def _column_ddl(col) -> str:
    t = col["type_name"]
    if t in _SIZED_TYPES:
        length = "max" if col["max_length"] == -1 else (
            col["max_length"] // 2 if t in ("nvarchar", "nchar") else col["max_length"]
        )
        t = f"{t}({length})"
    elif t in _PRECISION_TYPES:
        t = f"{t}({col['precision']},{col['scale']})"
    nullability = "NULL" if col["is_nullable"] else "NOT NULL"
    return f"    [{col['name']}] {t} {nullability}"


def script_to_sql(db_name: str, out_path, log, side=None) -> str:
    label = side["database"] if side and side.get("kind") == "live" else db_name
    log(f"scripting [{label}] to .sql ({out_path.name})...")
    conn = _connect(db_name, side)
    cur = conn.cursor(as_dict=True)

    lines = [f"-- Schema snapshot of [{db_name}], generated by drift-tool.",
              "-- Tables: reconstructed (columns + PK only -- not a full restore-quality dump).",
              "-- Procedures/views/functions/triggers: exact original source (sys.sql_modules).\n"]

    cur.execute(_TABLES_QUERY)
    tables = cur.fetchall()
    for t in tables:
        full_name = f"[{t['schema_name']}].[{t['table_name']}]"
        cur.execute(_COLUMNS_QUERY, (full_name,))
        cols = cur.fetchall()
        pk_cols = [c["name"] for c in cols if c["is_pk"]]
        col_lines = [_column_ddl(c) for c in cols]
        if pk_cols:
            col_lines.append(f"    PRIMARY KEY ({', '.join(f'[{c}]' for c in pk_cols)})")
        lines.append(f"CREATE TABLE {full_name} (\n" + ",\n".join(col_lines) + "\n);\nGO\n")

    cur.execute(_PROGRAMMABLE_QUERY)
    encrypted = 0
    for row in cur.fetchall():
        if row["definition"] is None:
            # WITH ENCRYPTION -> sys.sql_modules.definition is NULL. Must not
            # crash the whole export (.strip() on None) or silently drop the
            # object -- note it explicitly instead, same "never silently
            # treat as same/absent" standard as inspect_objects.get_encrypted_names.
            encrypted += 1
            lines.append(f"-- [{row['schema_name']}].[{row['obj_name']}] ({row['type_desc']}) is WITH ENCRYPTION "
                          f"-- definition unavailable, cannot script.\n")
            continue
        lines.append(row["definition"].strip() + "\nGO\n")
    if encrypted:
        log(f"  {encrypted} encrypted object(s) noted, not scripted (definition unavailable)")

    conn.close()
    out_path.write_text("\n".join(lines), encoding="utf-8")
    size_kb = out_path.stat().st_size / 1024
    log(f"  wrote {out_path.name} ({size_kb:.0f} KB, {len(tables)} table(s))")
    return str(out_path)
